default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root@123
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: blog_development

